### PR TITLE
Basic Styling

### PR DESCRIPTION
**Pull request by megamos**
Still lots to do, like fonts, sidebar, get the proper images.

But would be best for me to know what the site is intended to do,
before spending more time on it.

### CODE REVIEW

**Comment by jherrlin** [comment]
@megamos Should we merge this now or wait for more the sidebar on the index page?

**Comment by megamos** [comment]
Sure, I can try to get that done today.

**Comment by jherrlin** [comment]
Awesome, then i merge and publish tomorrow :)

**Comment by jherrlin** [comment]
Really awesome work @megamos !

**Comment by megamos** [comment]
Thanks buddy. Its an ugly beginning :)
Upgrades soon to come.

**Pull request merged**
